version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    # Disable version updates for gomod dependencies
    # We expect that any security alert will be listed in the security area but no automatic PR generation
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    # Disable version updates for npm dependencies
    # We expect that any security alert will be listed in the security area but no automatic PR generation
    open-pull-requests-limit: 0
